run:
  allow-parallel-runners: true

linters:
  enable:
    - asasalint
    - dupl
    - durationcheck
    - forbidigo
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - lll
    - revive
    - varnamelen

linters-settings:
  forbidigo:
    exclude_godoc_examples: true
  funlen:
    lines: 200
    statements: 160
  goconst:
    min-len: 5
  lll:
    line-length: 100
    tab-width: 8
  revive:
    rules:
      - name: redefines-builtin-id
        disabled: true
  varnamelen:
    max-distance: 20
    min-name-length: 2
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-decls:
      - t testing.T
      - i int
      - T any

issues:
  exclude-rules:
    - linters: [gocritic]
      text: "dupSubExpr: suspicious identical LHS and RHS for `==` operator"
      source: 'C.JS'
